#!/bin/bash

# --- COLOR DEFINITIONS ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# --- 0. LOCATION ENFORCER ---
REQUIRED_DIR="$HOME/servarr-stack"
CURRENT_DIR=$(pwd)

if [[ "$(realpath "$CURRENT_DIR")" != "$(realpath -m "$REQUIRED_DIR")" ]]; then
    echo -e "${RED}LOCATION ERROR:${NC} Please run this script from: ${YELLOW}$REQUIRED_DIR${NC}"
    echo "You are currently at: $CURRENT_DIR"
    exit 1
fi

# --- 1. DIRECTORY CHECK ---
if [ ! -f "docker-compose.yml" ]; then
    echo -e "${RED}ERROR:${NC} Could not find 'docker-compose.yml'."
    echo "Please ensure you cloned the repository correctly."
    exit 1
fi

# --- 2. GATHER USER INPUTS ---
echo "========================================"
echo "   SERVARR STACK CONFIGURATOR"
echo "========================================"

prompt_user() {
    local var_name=$1
    local default_val=$2
    local desc=$3
    echo -e "\n--- $var_name ---"
    echo -e "$desc"
    echo -e "Default: ${YELLOW}$default_val${NC}"
    # Standard read waits for Enter key
    read -p "Enter value: " input
    if [ -z "$input" ]; then USER_INPUT="$default_val"; else USER_INPUT="$input"; fi
}

# Defaults
DEFAULT_PUID=$(id -u)
DEFAULT_PGID=$(id -g)
DEFAULT_TZ="America/New_York"

# Inputs
prompt_user "PUID" "$DEFAULT_PUID" "User ID for file permissions"
VAL_PUID=$USER_INPUT

prompt_user "PGID" "$DEFAULT_PGID" "Group ID for file permissions"
VAL_PGID=$USER_INPUT

prompt_user "TZ" "$DEFAULT_TZ" "System Timezone"
VAL_TZ=$USER_INPUT

# Network Detection
echo -e "\n--- NETWORK CONFIGURATION ---"
DEFAULT_IFACE=$(ip route | grep '^default' | awk '{print $5}' | head -n 1)
DETECTED_SUBNET=$(ip route | grep "dev $DEFAULT_IFACE" | grep -v "^default" | awk '{print $1}' | head -n 1)
[ -z "$DETECTED_SUBNET" ] && DETECTED_SUBNET="192.168.1.0/24"

prompt_user "LOCAL_SUBNET" "$DETECTED_SUBNET" "Your LAN Subnet (Required for WebUI access)"
VAL_SUBNET=$USER_INPUT

echo -e "\n--- VPN CONFIGURATION ---"
echo "Select your VPN Provider from the list below."
echo "Type the number and press ENTER."

options=("airvpn" "cyberghost" "expressvpn" "fastestvpn" "hidemyass" "ipvanish" "ivpn" "mullvad" "nordvpn" "perfectprivacy" "privado" "privateinternetaccess" "privatevpn" "protonvpn" "purevpn" "surfshark" "tororg" "torguard" "vpnunlimited" "vyprvpn" "windscribe" "Other/Custom")

select opt in "${options[@]}"
do
    case $opt in
        "Other/Custom")
            read -p "Type provider name and press ENTER: " VAL_PROVIDER
            break
            ;;
        *)
            if [ -n "$opt" ]; then
                VAL_PROVIDER=$opt
                break
            else
                echo "Invalid option. Please try again."
            fi
            ;;
    esac
done
echo -e "${GREEN}Selected Provider: $VAL_PROVIDER${NC}"

prompt_user "SERVER_COUNTRIES" "Netherlands" "VPN Server Country"
VAL_COUNTRIES=$USER_INPUT

echo -e "\n--- VPN PROTOCOL ---"
echo "1) OpenVPN"
echo "2) WireGuard"
read -p "Select Protocol [1-2]: " PROTO_SELECTION

if [[ "$PROTO_SELECTION" == "2" ]]; then
    VAL_TYPE="wireguard"
    echo -e "${GREEN}Protocol: WireGuard${NC}"
    echo ""
    read -p "Enter WireGuard Private Key: " VAL_WG_KEY
    read -p "Enter WireGuard IPv4 Address (Optional): " VAL_WG_ADDR
else
    VAL_TYPE="openvpn"
    echo -e "${GREEN}Protocol: OpenVPN${NC}"
    echo ""
    read -p "Enter VPN Username: " VAL_VPN_USER
    read -p "Enter VPN Password: " VAL_VPN_PASS
fi

echo -e "\n${BLUE}Generating configuration file...${NC}"
ENV_FILE=".env"

cat > "$ENV_FILE" <<EOF
# --- CONFIGURATION GENERATED BY SETUP.SH ---
PUID=$VAL_PUID
PGID=$VAL_PGID
TZ=$VAL_TZ
LOCAL_SUBNET=$VAL_SUBNET

# Relative Paths (Do not change unless you know what you are doing)
CONFIG_ROOT=./.config
DATA_ROOT=./data

# Ports
WEBUI_PORT=8091
TORRENTING_PORT=6881

# VPN Settings
VPN_SERVICE_PROVIDER=$VAL_PROVIDER
VPN_TYPE=$VAL_TYPE
SERVER_COUNTRIES=$VAL_COUNTRIES
EOF

if [ "$VAL_TYPE" == "wireguard" ]; then
    echo "WIREGUARD_PRIVATE_KEY=$VAL_WG_KEY" >> "$ENV_FILE"
    if [ -n "$VAL_WG_ADDR" ]; then
        echo "WIREGUARD_ADDRESSES=$VAL_WG_ADDR" >> "$ENV_FILE"
    fi
else
    echo "OPENVPN_USER=$VAL_VPN_USER" >> "$ENV_FILE"
    echo "OPENVPN_PASSWORD=$VAL_VPN_PASS" >> "$ENV_FILE"
fi

echo -e "${BLUE}Applying permissions to data folders...${NC}"
sudo chown -R "$VAL_PUID:$VAL_PGID" .config data
sudo chmod -R 775 .config data

echo "========================================"
echo -e "${GREEN}   CONFIGURATION COMPLETE${NC}"
echo "========================================"
echo ""
echo -e "${YELLOW}Please verify the generated .env file below:${NC}"
echo "----------------------------------------"
cat "$ENV_FILE"
echo "----------------------------------------"
echo ""
echo "If everything looks correct, start your stack with:"
echo -e "${GREEN}docker compose up -d${NC}"
echo ""